[package]
name = "monoidal-categories-reboot"
version = "0.1"
lean_version = "3.4.2"
path = "src"

[dependencies]
lean-rewrite-search = {git = "https://github.com/semorrison/lean-rewrite-search", branch = "old-working-version", rev = "4221c65ed7cc2d96cb9fd7278b9f8746a8843aac"}
lean-category-theory = {git = "https://github.com/semorrison/lean-category-theory", branch = "master", rev = "0151052845e1f5bc61fc409b6418598d3ff37280"}
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "4263b2be91c453051aa5790d10fb454a9785fe35"}
